### ISSUE TITLE
`hdocs` incorrectly claims to work with `haddock-*-1.2`

### ISSUE THREAD

**Issue by hvr** [mvoidex/hdocs#4]
See https://github.com/haskell/haddock/issues/366#issuecomment-87136891

**Comment by mvoidex** [comment]
Thanks

**Comment by mvoidex** [comment]
Set upper bounds in https://github.com/mvoidex/hdocs/commit/08ea13724da944ff27890fcdc26aa5ee8849b393

**Comment by hvr** [comment]
In order for this to have any useful effect on Hackage (if you upload it) you'd have to retrofit upper bounds on all existing `hdocs` releases, otherwise the cabal-solver will simply fallback to an older `hdocs` release which didn't yet have the upper bound.

If you want, I can take care of it

**Comment by mvoidex** [comment]
I've uploaded 4.1.3 with updated dep. Is it enough to set haddock-api to `>=2.15.0 && <2.16.0` (for hdocs 4.1.* ) and `>=2.14.0 && <2.15.0` (hdocs 4.0.* )?

> If you want, I can take care of retrofitting missing upper bounds

It'll be great

**Comment by hvr** [comment]
> Is it enough to set haddock-api to >=2.15.0 && <2.16.0 (for hdocs 4.1.* ) and >=2.14.0 && <2.15.0 (hdocs 4.0.* )? 

yeah... and I did that already; now `cabal install 'hdocs < 0.4.2'` will fail to find any install-plan w/ GHC 7.10.1
